Repository 4NTJ/Quiet, pull requests merged in 2022-08, with the labels that each got.

#5 [ADD] 검색 창 레이아웃 구성
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Extension/UIViewController+Extension.swift
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Global/UIComponents/BackButton.swift
  Quiet/Quiet/Screens/Search/Cell/RecentKeywordTableViewCell.swift
  Quiet/Quiet/Screens/Search/Component/RecentKeywordHeaderView.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
Labels: 🍊 Duna, 🏞 UI

#7 [ADD] Charts 라이브러리 추가 후 line chart, bar chart 테스트
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Utils/UIView+Preview.swift
  Quiet/Quiet/Global/Utils/UIViewController+Preview.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartView.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseLineChartView.swift
  Quiet/Quiet/Screens/Detail/NoiseLineChartViewController.swift
Labels: 🍊 Dani, 🏞 UI

#19 [DEL] 색상 Extension 삭제
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Quiet/Quiet/Global/Extension/UIColor+Extension.swift
Labels: 🍊 Duna

#14 [ADD] 맵뷰 UI 구현하기
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/UIComponents/CircleButton.swift
  Quiet/Quiet/Screens/Map/MapViewController.swift
  Quiet/Quiet/Screens/Map/SearchBarView.swift
Labels: 🍊 Miller, 🏞 UI

#13 [FEAT] 최근 검색어 저장, 삭제 기능 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Network/Storage/UserDefaultHandler.swift
  Quiet/Quiet/Network/Storage/UserDefaultStorage.swift
  Quiet/Quiet/Screens/Search/Cell/RecentKeywordTableViewCell.swift
  Quiet/Quiet/Screens/Search/Component/RecentKeywordHeaderView.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#22 [FEAT] 현재위치로 이동 구현
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/Supports/Info.plist
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller, ⚪️ Logic

#18 [ADD] 소음 분류 manual 뷰 구현하기
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Extension/UILabel+Extension.swift
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Map/Component/Noise.swift
  Quiet/Quiet/Screens/Map/Component/NoiseInfoView.swift
  Quiet/Quiet/Screens/Map/ManualViewController.swift
Labels: 🍊 Miller, 🏞 UI, 🧬 Model, ⚪️ Logic

#24 [CORRECT] safeArea기준으로 버튼 제약레이아웃 변경
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller

#21 [FEAT] Location Search 기능 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Screens/Search/Cell/SearchTableViewCell.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#30 [ADD] manual NavBar UI 및 map,maual 뷰컨 연결
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Map/ManualViewController.swift
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller, 🏞 UI

#28 [ADD] 앱 아이콘 추가
  Quiet/Quiet/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Quiet/Quiet/Global/Resources/Assets.xcassets/AppIcon.appiconset/QuietIcon.png
Labels: 🍊 Dani

#32 [CHORE] searchField 타입 교체 및 뷰연결
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Map/MapViewController.swift
  Quiet/Quiet/Screens/Map/SearchBarView.swift
Labels: 🍊 Miller, ⚪️ Logic

#25 [FEAT] 결과 화면 생성 및 데이터 연결
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Base/BaseViewController.swift
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Screens/Search/Cell/LocationDetailTableViewCell.swift
  Quiet/Quiet/Screens/Search/Cell/SearchTableViewCell.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SearchResultViewController.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
  Quiet/Quiet/Screens/Search/VC/SheetViewController.swift
Labels: 🍊 Duna, 🏞 UI, ⚪️ Logic

#35 [FIX] 메뉴얼 네비게이션바 안보이는 문제 해결
  Quiet/Quiet/Screens/Map/ManualViewController.swift
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🐞 Bug, 🍊 Miller

#39 [ADD] 상세 소음정보 화면 UI 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartView.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseLineChartView.swift
  Quiet/Quiet/Screens/Detail/NoiseLineChartViewController.swift
Labels: 🍊 Dani, 🏞 UI

#41 [FEAT] manual 사운드 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/Resources/Sound/Blue.mp3
  Quiet/Quiet/Global/Resources/Sound/Gray.mp3
  Quiet/Quiet/Global/Resources/Sound/Green.mp3
  Quiet/Quiet/Global/Resources/Sound/Red.mp3
  Quiet/Quiet/Global/Resources/Sound/Yellow.mp3
  Quiet/Quiet/Network/Storage/UserDefaultStorage.swift
  Quiet/Quiet/Screens/Map/Component/Noise.swift
  Quiet/Quiet/Screens/Map/Component/NoiseInfoView.swift
  Quiet/Quiet/Screens/Map/ManualViewController.swift
Labels: 🍊 Miller, ⚪️ Logic

#42 [FEAT] 검색어에 따라서 뷰가 다르게 보이도록 구현
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#37 [ADD] 서버 Foundation 코드 및 서버 연결 코드 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Quiet/Quiet/Global/Extension/Encodable+Extension.swift
  Quiet/Quiet/Global/Supports/Info.plist
  Quiet/Quiet/Network/API/IoTAPI.swift
  Quiet/Quiet/Network/APIService/IoTService.swift
  Quiet/Quiet/Network/Foundation/GeneralAPI.swift
  Quiet/Quiet/Network/Foundation/NetworkLoggerPlugin.swift
  Quiet/Quiet/Network/Model/ColDescInfo.swift
  Quiet/Quiet/Network/Model/DatasetInfo.swift
  Quiet/Quiet/Network/Model/InquiryInfo.swift
  Quiet/Quiet/Network/Model/InquiryQuery.swift
  Quiet/Quiet/Network/Model/InstallInfo.swift
Labels: 🍊 Duna, 🧬 Model

#44 [FEAT] searchMap과 manualView 연결
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
Labels: 🍊 Miller, 🏞 UI

#45 [ADD] Launchscreen 만들기
  Quiet/Quiet/Global/Resources/Assets.xcassets/SplashIcon.imageset/Contents.json
  Quiet/Quiet/Global/Resources/Assets.xcassets/SplashIcon.imageset/QuietIcon.png
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/LaunchScreen.storyboard
Labels: 🍊 Dani

#49 [CHORE] 앱 아이콘 교체
  Quiet/Quiet/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Quiet/Quiet/Global/Resources/Assets.xcassets/AppIcon.appiconset/Quiet Icon.png
  Quiet/Quiet/Global/Resources/Assets.xcassets/AppIcon.appiconset/QuietIcon.png
  Quiet/Quiet/Global/Resources/Assets.xcassets/SplashIcon.imageset/Contents.json
  Quiet/Quiet/Global/Resources/Assets.xcassets/SplashIcon.imageset/Quiet Icon.png
  Quiet/Quiet/Global/Resources/Assets.xcassets/SplashIcon.imageset/QuietIcon.png
Labels: 🍊 Dani

#51 [FEAT] 동을 검색했을 때 결과 데이터 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Literals/ImageLiteral.swift
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Network/API/IoTAPI.swift
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Search/Cell/LocationDetailTableViewCell.swift
  Quiet/Quiet/Screens/Search/Component/AnnoationView.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SearchResultViewController.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#53 [ADD] 상세 소음정보 화면에 스크롤뷰 적용
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
Labels: 🍊 Dani, 🏞 UI

#56 [CHORE] 초기 현재위치 확대 및 현재위치버튼 fill이미지로 초기화
  Quiet/Quiet/Global/Resources/Storyboard/Base.lproj/Main.storyboard
  Quiet/Quiet/Screens/Map/MapViewController.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
Labels: 🍊 Miller, 🏞 UI, ⚪️ Logic

#59 [FEAT] 검색 결과 뷰에 마커 표시, Bottom Sheet 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Extension/Date+Extension.swift
  Quiet/Quiet/Global/Extension/Notification+Extension.swift
  Quiet/Quiet/Global/UIComponents/AnnoationView.swift
  Quiet/Quiet/Network/API/IoTAPI.swift
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Map/SearchBarView.swift
  Quiet/Quiet/Screens/Search/Cell/LocationDetailTableViewCell.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#63 [FIX] 상세 소음정보 화면 수정
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartView.swift
Labels: 🍊 Dani, 🏞 UI

#61 [ADD] 로티 적용 및 행정동 변경
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Quiet/Quiet/Global/Base/BaseViewController.swift
  Quiet/Quiet/Global/Extension/Notification+Extension.swift
  Quiet/Quiet/Global/Resources/Lottie/dots.json
  Quiet/Quiet/Screens/Map/SearchBarView.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SearchResultViewController.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#66 [FEAT] 상세 소음정보 화면에서 데이터 가져와서 적용
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartView.swift
Labels: 🍊 Dani

#67 [FEAT] 맵뷰에 측정장치위치 표시하기
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Screens/Map/Component/SelectedInfoView.swift
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller, 🏞 UI, ⚪️ Logic

#64 [FIX] 최근 검색어에서 셀을 누르면 터지는 문제 해결
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Network/Storage/UserDefaultHandler.swift
  Quiet/Quiet/Network/Storage/UserDefaultStorage.swift
  Quiet/Quiet/Screens/Search/SearchViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
Labels: 🐞 Bug, 🍊 Duna

#71 [FEAT] 검색 결과 뷰에서 상세 뷰로 데이터 전달 구현
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Global/Extension/Notification+Extension.swift
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Map/MapViewController.swift
  Quiet/Quiet/Screens/Search/SearchMapViewController.swift
  Quiet/Quiet/Screens/Search/SheetContainerViewController.swift
Labels: 🍊 Duna, ⚪️ Logic

#73 [FEAT] lottie 적용
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller, 🏞 UI

#75 급한 차트 문제 수정
  Quiet/Quiet.xcodeproj/project.pbxproj
  Quiet/Quiet/Screens/Detail/DetailViewController.swift
  Quiet/Quiet/Screens/Detail/NoiseBarChartView.swift
  Quiet/Quiet/Screens/Detail/NoiseLineChartView.swift
Labels: 🐞 Bug

#77 [ADD] 맵뷰와 디테일 연결
  Quiet/Quiet/Screens/Map/MapViewController.swift
Labels: 🍊 Miller, 🏞 UI
